More texts and options customization
hugolgst/vimsence pull request #38
Opened 2021-03-10 14:34 UTC by sglkc

Users can now modify almost every presence texts, also more support for users with custom client.
Some codes may need optimizations, as I'm _not_ too familiar with python...

2021-03-10 19:44 UTC, hugolgst commented
@anned20 Could you also review it?

2021-03-12 15:00 UTC, anned20 requested changes
Didn't test it yet, but the code looks good.

2021-03-13 03:56 UTC, sglkc commented on python/vimsence.py
> +    def replace_text(string):
I've renamed `replace_text` function to `parse_tags`, this should solve the request

2021-03-13 04:14 UTC, sglkc reviewed
Renamed `replace_text` to `parse_tags`

2021-03-14 10:42 UTC, anned20 requested changes
There has been a change in code style in the master branch.

Please update your code to use that coding style and run the pre-commit hook, description on how to do that can be found in the README.md.

Please rebase and squash your commits too after doing this.

2021-08-17 14:55 UTC, closed without merging